name: Build and Release DbStudio

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    env:
      Solution_Name: DbStudio.sln
      DbStudio_Project: DbStudio/DbStudio.csproj
      Updater_Project: DbStudio.Updater/DbStudio.Updater.csproj
      Output_Dir: output


    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore ${{ env.Solution_Name }}


    # Publish DbStudio to output/DbStudio
    - name: Publish DbStudio
      run: dotnet publish ${{ env.DbStudio_Project }} --configuration Release --output ${{ env.Output_Dir }}/DbStudio

    # Publish Updater to output/Updater
    - name: Publish Updater
      run: dotnet publish ${{ env.Updater_Project }} --configuration Release --output ${{ env.Output_Dir }}/Updater

    # Zip each individually
    - name: Zip DbStudio
      run: Compress-Archive -Path ${{ env.Output_Dir }}/DbStudio/* -DestinationPath DbStudio.zip

    - name: Zip Updater
      run: Compress-Archive -Path ${{ env.Output_Dir }}/Updater/* -DestinationPath Updater.zip

    # Create the final versioned ZIP with both zip files inside
    - name: Create Final Release Bundle
      run: |
        New-Item -ItemType Directory -Path Bundle
        Copy-Item -Path DbStudio.zip -Destination Bundle/
        Copy-Item -Path Updater.zip -Destination Bundle/
        Compress-Archive -Path Bundle/* -DestinationPath DbStudio_Release.zip

    - name: Upload Final ZIP to GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: DbStudio_Release.zip
        token: ${{ secrets.GITHUB_TOKEN }}
